"""initial schema

Revision ID: 10810fac474c
Revises: 
Create Date: 2026-07-26 21:26:50.184075
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from apps.api.app.db.types import GUID, JSONB, UTCDateTime  # noqa: F401

revision: str = '10810fac474c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_versions',
    sa.Column('semantic_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'retired', name='curriculum_status', native_enum=False, length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', UTCDateTime(), nullable=True),
    sa.Column('metadata_json', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_versions')),
    sa.UniqueConstraint('semantic_version', name='uq_curriculum_versions_semantic_version')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status', native_enum=False, length=64), nullable=False),
    sa.Column('last_login_at', UTCDateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('error_patterns',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=128), nullable=False),
    sa.Column('canonical_description', sa.Text(), nullable=False),
    sa.Column('first_seen_at', UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', UTCDateTime(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('current_priority', sa.Float(), nullable=False),
    sa.Column('blocks_meaning', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'improving', 'resolved', name='error_status', native_enum=False, length=64), nullable=False),
    sa.Column('examples', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_error_patterns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_patterns')),
    sa.UniqueConstraint('user_id', 'taxonomy_code', name='uq_error_patterns_user_code')
    )
    with op.batch_alter_table('error_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_patterns_user_id'), ['user_id'], unique=False)

    op.create_table('learner_profiles',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('explanation_language', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('target_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level', native_enum=False, length=64), nullable=False),
    sa.Column('goals', JSONB(), nullable=False),
    sa.Column('interests', JSONB(), nullable=False),
    sa.Column('accessibility_preferences', JSONB(), nullable=False),
    sa.Column('privacy_preferences', JSONB(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_learner_profiles'))
    )
    op.create_table('plans',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('requested_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'expired', name='plan_status', native_enum=False, length=64), nullable=False),
    sa.Column('rationale', JSONB(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('user_id', 'plan_date', name='uq_plans_user_date')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('review_queue',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('memory_object_type', sa.Enum('lexical_entry', 'phrase', 'skill_node', 'error_pattern', name='memory_object_type', native_enum=False, length=64), nullable=False),
    sa.Column('memory_object_key', sa.String(length=160), nullable=False),
    sa.Column('review_mode', sa.Enum('meaning_recognition', 'form_recognition', 'form_recall', 'meaning_recall', 'listening_recognition', 'pronunciation_production', 'contextual_production', name='review_mode', native_enum=False, length=64), nullable=False),
    sa.Column('due_at', UTCDateTime(), nullable=False),
    sa.Column('last_reviewed_at', UTCDateTime(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('scheduler_version', sa.String(length=32), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint('difficulty >= 0 AND difficulty <= 1', name=op.f('ck_review_queue_difficulty_bounded')),
    sa.CheckConstraint('stability >= 0', name=op.f('ck_review_queue_stability_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_queue_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue')),
    sa.UniqueConstraint('user_id', 'memory_object_type', 'memory_object_key', 'review_mode', name='uq_review_queue_object_mode')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_user_id'), ['user_id'], unique=False)

    op.create_table('skill_nodes',
    sa.Column('curriculum_version_id', GUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.Enum('listening', 'spoken_production', 'spoken_interaction', 'pronunciation', 'reading', 'written_production', 'written_interaction', 'vocabulary', 'grammar', 'fluency', 'discourse', 'pragmatics', 'mediation', 'learning_strategies', name='skill_domain', native_enum=False, length=64), nullable=False),
    sa.Column('subdomain', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cefr_min', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level', native_enum=False, length=64), nullable=False),
    sa.Column('cefr_max', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level', native_enum=False, length=64), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('metadata_json', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_skill_nodes_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_nodes')),
    sa.UniqueConstraint('curriculum_version_id', 'key', name='uq_skill_nodes_version_key')
    )
    with op.batch_alter_table('skill_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_nodes_curriculum_version_id'), ['curriculum_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_nodes_key'), ['key'], unique=False)

    op.create_table('learning_objectives',
    sa.Column('skill_node_id', GUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('can_do', sa.Text(), nullable=False),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level', native_enum=False, length=64), nullable=False),
    sa.Column('min_contexts', sa.Integer(), nullable=False),
    sa.Column('evidence_requirements', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], name=op.f('fk_learning_objectives_skill_node_id_skill_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_objectives')),
    sa.UniqueConstraint('skill_node_id', 'key', name='uq_learning_objectives_node_key')
    )
    with op.batch_alter_table('learning_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_objectives_skill_node_id'), ['skill_node_id'], unique=False)

    op.create_table('learning_sessions',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('plan_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='session_status', native_enum=False, length=64), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('ended_at', UTCDateTime(), nullable=True),
    sa.Column('context', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_learning_sessions_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('plan_items',
    sa.Column('plan_id', GUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('activity_key', sa.String(length=128), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('reason_codes', JSONB(), nullable=False),
    sa.Column('priority_components', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.CheckConstraint('estimated_minutes > 0', name=op.f('ck_plan_items_estimated_minutes_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_items_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items')),
    sa.UniqueConstraint('plan_id', 'sequence', name='uq_plan_items_plan_sequence')
    )
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_items_plan_id'), ['plan_id'], unique=False)

    op.create_table('skill_edges',
    sa.Column('from_skill_id', GUID(), nullable=False),
    sa.Column('to_skill_id', GUID(), nullable=False),
    sa.Column('relation', sa.Enum('prerequisite', 'supports', 'confusable', 'transfer', name='skill_relation', native_enum=False, length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_skill_id'], ['skill_nodes.id'], name=op.f('fk_skill_edges_from_skill_id_skill_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_skill_id'], ['skill_nodes.id'], name=op.f('fk_skill_edges_to_skill_id_skill_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_edges')),
    sa.UniqueConstraint('from_skill_id', 'to_skill_id', 'relation', name='uq_skill_edges_triple')
    )
    with op.batch_alter_table('skill_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_edges_from_skill_id'), ['from_skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_edges_to_skill_id'), ['to_skill_id'], unique=False)

    op.create_table('skill_states',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('skill_node_id', GUID(), nullable=False),
    sa.Column('mastery_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('distinct_contexts', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_observed_at', UTCDateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_skill_states_confidence_bounded')),
    sa.CheckConstraint('mastery_probability >= 0 AND mastery_probability <= 1', name=op.f('ck_skill_states_mastery_probability_bounded')),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], name=op.f('fk_skill_states_skill_node_id_skill_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_skill_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_node_id', name=op.f('pk_skill_states'))
    )
    op.create_table('attempts',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('activity_key', sa.String(length=128), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('response', JSONB(), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('submitted_at', UTCDateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('scaffolding_level', sa.Float(), nullable=False),
    sa.Column('evaluator_id', sa.String(length=128), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_attempts_attempt_number_positive')),
    sa.CheckConstraint('hints_used >= 0', name=op.f('ck_attempts_hints_used_non_negative')),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_attempts_session_id_learning_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    sa.UniqueConstraint('session_id', 'activity_key', 'attempt_number', name='uq_attempts_session_activity')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('evidence_events',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('skill_node_id', GUID(), nullable=False),
    sa.Column('attempt_id', GUID(), nullable=True),
    sa.Column('evidence_type', sa.Enum('recognition', 'controlled_recall', 'contextual_production', 'comprehension', 'interaction', 'transfer', 'benchmark', 'self_report', name='evidence_type', native_enum=False, length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('independence', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('context_key', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', UTCDateTime(), nullable=False),
    sa.Column('metadata_json', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_evidence_events_confidence_bounded')),
    sa.CheckConstraint('independence >= 0 AND independence <= 1', name=op.f('ck_evidence_events_independence_bounded')),
    sa.CheckConstraint('novelty >= 0 AND novelty <= 1', name=op.f('ck_evidence_events_novelty_bounded')),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_evidence_events_score_bounded')),
    sa.CheckConstraint('weight >= 0', name=op.f('ck_evidence_events_weight_non_negative')),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_evidence_events_attempt_id_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], name=op.f('fk_evidence_events_skill_node_id_skill_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_evidence_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_events'))
    )
    with op.batch_alter_table('evidence_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_events_skill_node_id'), ['skill_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_events_skill_node_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_events_occurred_at'))

    op.drop_table('evidence_events')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_session_id'))

    op.drop_table('attempts')
    op.drop_table('skill_states')
    with op.batch_alter_table('skill_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_edges_to_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_edges_from_skill_id'))

    op.drop_table('skill_edges')
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_items_plan_id'))

    op.drop_table('plan_items')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_sessions_user_id'))

    op.drop_table('learning_sessions')
    with op.batch_alter_table('learning_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_objectives_skill_node_id'))

    op.drop_table('learning_objectives')
    with op.batch_alter_table('skill_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_nodes_key'))
        batch_op.drop_index(batch_op.f('ix_skill_nodes_curriculum_version_id'))

    op.drop_table('skill_nodes')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_queue_due_at'))

    op.drop_table('review_queue')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))

    op.drop_table('plans')
    op.drop_table('learner_profiles')
    with op.batch_alter_table('error_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_patterns_user_id'))

    op.drop_table('error_patterns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('curriculum_versions')
    # ### end Alembic commands ###
